  
services:
  whisperx-api-test:
    image: reg.securityzone.vn/sonnguyen/whisperx-api:latest
    container_name: whisperx-api-test
    ports:
      - "5773:5772"
    environment:
      - PORT=5772
      - TIMEOUT_SECONDS=1200
      - DEFAULT_MODEL=large-v3
      - DEBUG=false
      - LD_LIBRARY_PATH=/usr/local/lib/python3.10/dist-packages/nvidia/cudnn/lib
    command: ["python", "app2.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    volumes:
      - ~/.cache/huggingface:/root/.cache  # Cache models to avoid re-downloading
      - ./app2.py:/app/app2.py  # Mount app2.py into container
